export type CaseStudy = {
  slug: string
  provider: string
  title: string
  council: string
  contractType: string
  category: string
  categoryLabel: string
  accentColor: string
  transformation: string
  startingPosition: string
  complexity: string
  result: string
  lots: string
  image: string
}

export const CASE_STUDIES: CaseStudy[] = [
  {
    slug: 'bedford-supported-living-framework',
    provider: 'Havilah Care',
    title: 'Bedford Supported Living and Community Based Support Framework 2025',
    council: 'Bedford Borough Council',
    contractType: 'Framework',
    category: 'supported-living',
    categoryLabel: 'Supported Living',
    accentColor: '#B02727',
    transformation: 'From 1 of 154 applicants → 1 of 44 successful providers, all three lots awarded.',
    startingPosition: 'Owner-led growing provider. Sub-30 percent acceptance rate framework. Case study sub-points implied rather than evidenced.',
    complexity: 'Gateway selection, high competition',
    result: '1 of 44 from 154',
    lots: '3 lots awarded',
    image: '/Page Content HTML Files/assets/feedback/c4-1.png',
  },
  {
    slug: 'essex-domiciliary-framework-2025',
    provider: 'Choices Healthcare',
    title: 'Essex Live at Home Domiciliary Framework 2025 — Five Tier 2 Lots',
    council: 'Essex County Council',
    contractType: 'Framework',
    category: 'domiciliary',
    categoryLabel: 'Domiciliary Care',
    accentColor: '#C25E1F',
    transformation: 'From no Essex framework footprint → awarded 5 Tier 2 lots.',
    startingPosition: 'Tier 1 not achievable at close. Digital systems active operationally but unpacked for evaluator review.',
    complexity: 'Multi-lot, deterministic banding',
    result: '5 Tier 2 lots',
    lots: '5 lots awarded',
    image: '/Page Content HTML Files/assets/feedback/c2-01.png',
  },
  {
    slug: 'dorset-care-support-open-framework',
    provider: 'Inspire Care Outreach',
    title: 'Dorset Care, Support, Housing and Community Safety Open Framework 2024 — Five Lots',
    council: 'Dorset Council',
    contractType: 'Open Framework',
    category: 'multi-service',
    categoryLabel: 'Multi-Service Care',
    accentColor: '#0A6E5A',
    transformation: 'From cohort-blind generic answers → awarded 5 lots on first application.',
    startingPosition: 'Single set of generic answers stretched across five distinct cohort lots. Live-in cover bundled into domiciliary content.',
    complexity: 'Multi-lot, multi-cohort',
    result: '5 lots on first application',
    lots: '5 lots awarded',
    image: '/Page Content HTML Files/assets/feedback/c6-1.png',
  },
  {
    slug: 'bradford-mental-health-provider-list',
    provider: 'Rosecare',
    title: 'Bradford Mental Health Supported Living Provider List 2025',
    council: 'Bradford Council',
    contractType: 'Provider List',
    category: 'mental-health',
    categoryLabel: 'Mental Health',
    accentColor: '#5B3A8B',
    transformation: 'From mid-band drift on a 0–2 rubric → 6 of 8 questions at full marks, both lots awarded.',
    startingPosition: 'Quality answers written for an unwritten 0–5 gradient. Coproduction referenced rather than demonstrated.',
    complexity: 'Binary rubric precision',
    result: '6/8 full marks',
    lots: '2 lots awarded',
    image: '/Page Content HTML Files/assets/feedback/c8-1.png',
  },
  {
    slug: 'southend-childrens-residential-framework',
    provider: 'Choices Healthcare',
    title: "Southend-on-Sea Children's Residential and Accommodation Framework 2025–2028",
    council: 'Southend-on-Sea City Council',
    contractType: 'Framework',
    category: 'childrens',
    categoryLabel: "Children's Accommodation",
    accentColor: '#2E5E8C',
    transformation: "From adult-derived narrative → awarded Lot 2 D, E and F.",
    startingPosition: "Adult social care provider stretching into 18+ children's services. Adult-derived case examples and superseded policy citations.",
    complexity: 'High complexity, multi-sub-lot',
    result: 'Lot 2 D, E and F',
    lots: '3 sub-lots',
    image: '/Page Content HTML Files/assets/feedback/c3-1.png',
  },
  {
    slug: 'essex-live-at-home-tier-2-framework',
    provider: 'Livingstone Healthcare',
    title: 'Essex Live at Home Domiciliary Framework 2025 — Five Tier 2 Lots, Documented Tier 1 Path',
    council: 'Essex County Council',
    contractType: 'Framework',
    category: 'domiciliary',
    categoryLabel: 'Domiciliary Care',
    accentColor: '#C25E1F',
    transformation: 'From a procedural Tier 1 miss → awarded 5 Tier 2 lots, Tier 1 path documented.',
    startingPosition: 'Q9 Video evidence missing at first close. Clarification window passed without response. Tier 1 lost on procedural grounds.',
    complexity: 'Procedural recovery, multi-lot',
    result: '5 Tier 2 lots',
    lots: '5 lots awarded',
    image: '/Page Content HTML Files/assets/feedback/c7-01.png',
  },
  {
    slug: 'hertfordshire-cyp-homecare-framework',
    provider: 'In-Home Carers',
    title: 'Hertfordshire Children and Young People with Disabilities Homecare Framework',
    council: 'Hertfordshire County Council',
    contractType: 'Framework',
    category: 'childrens',
    categoryLabel: "Children's Homecare",
    accentColor: '#2E5E8C',
    transformation: 'From adult-derived defaults → both lots awarded by SEND Commissioning.',
    startingPosition: "Adult-derived homecare narrative applied to a children and young people SEND framework.",
    complexity: 'SEND panel fluency',
    result: 'Both lots awarded',
    lots: '2 lots awarded',
    image: '/Page Content HTML Files/assets/feedback/c5-1.png',
  },
  {
    slug: 'central-bedfordshire-supported-living',
    provider: 'Nelson Ocean',
    title: 'Central Bedfordshire Supported Living Direct Contract',
    council: 'Central Bedfordshire Council',
    contractType: 'Direct Contract',
    category: 'supported-living',
    categoryLabel: 'Supported Living',
    accentColor: '#B02727',
    transformation: 'From a generic supported living narrative → awarded Lot 1 with variable day hours led on the front foot.',
    startingPosition: 'Generic supported living narrative insufficient for MEAT-weighted cohort scoring.',
    complexity: 'Multi-cohort, MEAT-weighted',
    result: 'Lot 1 awarded',
    lots: '1 lot awarded',
    image: '/Page Content HTML Files/assets/feedback/c9-1.png',
  },
  {
    slug: 'childrens-services-direct-contract',
    provider: 'PCAS',
    title: "Local Authority Children's Services Direct Contract",
    council: "Local Authority Children's Services",
    contractType: 'Direct Contract',
    category: 'childrens',
    categoryLabel: "Children's Services",
    accentColor: '#2E5E8C',
    transformation: 'From adult-derived defaults → position awarded, Q2 Recruitment scored 4 of 5.',
    startingPosition: "Adult-derived defaults applied to a children's services rubric with a six-question technical structure.",
    complexity: 'Cohort recalibration, six-question rubric',
    result: 'Position awarded',
    lots: '1 position',
    image: '/Page Content HTML Files/assets/feedback/c10-1.png',
  },
  {
    slug: 'sheffield-dps-overnight-short-breaks',
    provider: 'Alicelyn',
    title: 'Sheffield Adults with Disabilities DPS, Lot 3 Overnight Short Breaks 2025',
    council: 'Sheffield City Council',
    contractType: 'DPS',
    category: 'adult-care',
    categoryLabel: 'Adult Social Care',
    accentColor: '#1F1F1F',
    transformation: 'From no Sheffield DPS footprint → awarded Lot 3 Overnight Short Breaks.',
    startingPosition: 'No prior place on the Sheffield DPS. Operationally strong, procurement-thin. No internal bid lead.',
    complexity: 'First-time DPS entry',
    result: 'Lot 3 awarded',
    lots: '1 lot awarded',
    image: '/Page Content HTML Files/assets/feedback/c1-1.png',
  },
]

export const CATEGORY_FILTERS = [
  { value: '',               label: 'All settings' },
  { value: 'supported-living', label: 'Supported Living' },
  { value: 'domiciliary',    label: 'Domiciliary Care' },
  { value: 'childrens',      label: "Children's Services" },
  { value: 'mental-health',  label: 'Mental Health' },
  { value: 'multi-service',  label: 'Multi-Service' },
  { value: 'adult-care',     label: 'Adult Social Care' },
]

export const CONTRACT_FILTERS = [
  { value: '',                label: 'All contract types' },
  { value: 'Framework',       label: 'Framework' },
  { value: 'Direct Contract', label: 'Direct Contract' },
  { value: 'Open Framework',  label: 'Open Framework' },
  { value: 'Provider List',   label: 'Provider List' },
  { value: 'DPS',             label: 'DPS' },
]

export const COUNCIL_FILTERS = [
  { value: '',                                     label: 'All councils' },
  { value: 'Bedford Borough Council',              label: 'Bedford Borough' },
  { value: 'Bradford Council',                     label: 'Bradford' },
  { value: 'Central Bedfordshire Council',         label: 'Central Bedfordshire' },
  { value: 'Dorset Council',                       label: 'Dorset' },
  { value: 'Essex County Council',                 label: 'Essex' },
  { value: 'Hertfordshire County Council',         label: 'Hertfordshire' },
  { value: "Local Authority Children's Services",  label: "LA Children's" },
  { value: 'Sheffield City Council',               label: 'Sheffield' },
  { value: 'Southend-on-Sea City Council',         label: 'Southend-on-Sea' },
]
