'use client'
import { FormEvent, useEffect, useState } from 'react'
import styles from '../resources.module.css'

type Profile = { organisation: string; services: string; geography: string; regulation: string; turnover: string; experience: string; workforce: string; evidence: string; mobilisation: string; updatedAt: string }
const empty: Profile = { organisation:'',services:'',geography:'',regulation:'',turnover:'',experience:'',workforce:'',evidence:'',mobilisation:'',updatedAt:'' }
const fields: Array<[keyof Profile,string,string]> = [
  ['organisation','Organisation','Legal status, years trading and any company details you choose to record.'],['services','Services','Current care settings and services, with planned services kept separate.'],['geography','Geography','Operating regions and a realistic mobilisation or travel radius.'],['regulation','Regulation','Relevant regulator, registered activities and current inspection position where applicable.'],['turnover','Financial capacity','Turnover band, accounts availability, insurance types and current limits.'],['experience','Comparable experience','Largest comparable contract, delivery scale, public or private-sector experience and verification routes.'],['workforce','Workforce','Headcount, vacancies, recruitment throughput, training and management capacity.'],['evidence','Evidence','Case studies, KPI records, outcomes, audits, complaints, safeguarding and quality records.'],['mobilisation','Mobilisation','Unused capacity, lead times, systems, office capacity, travel model and TUPE assumptions.'],
]
export default function OrganisationProfile(){const [profile,setProfile]=useState<Profile>(empty);const [saved,setSaved]=useState('');useEffect(()=>{try{const raw=localStorage.getItem('tenderlab-organisation-profile:v1');if(raw)setProfile(JSON.parse(raw) as Profile)}catch{}},[]);const submit=(event:FormEvent)=>{event.preventDefault();const next={...profile,updatedAt:new Date().toISOString()};localStorage.setItem('tenderlab-organisation-profile:v1',JSON.stringify(next));setProfile(next);setSaved('Profile saved on this device. Future tools can reuse it.')};return <form className={styles.profileForm} onSubmit={submit}>{fields.map(([key,label,help])=><label key={key}><span>{label}</span><small>{help}</small><textarea rows={3} value={profile[key]} onChange={event=>setProfile(current=>({...current,[key]:event.target.value}))}/></label>)}<div className={styles.profileActions}><button className={styles.primaryButton} type="submit">Save organisation profile</button><button className={styles.secondaryButton} type="button" onClick={()=>{localStorage.removeItem('tenderlab-organisation-profile:v1');setProfile(empty);setSaved('Saved profile removed from this device.')}}>Delete saved profile</button></div><p role="status" aria-live="polite">{saved}</p></form>}
